# Generated by Django 5.2.8 on 2025-11-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='state',
            field=models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Kerala', 'Kerala'), ('Karnataka', 'Karnataka'), ('Tamil Nadu', 'Tamil Nadu')], db_index=True, max_length=100),
        ),
    ]
