# Generated by Django 5.2.8 on 2026-01-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream', models.CharField(choices=[('ENGINEERING', 'Engineering'), ('MEDICAL', 'Medical'), ('ARTS AND SCIENCE', 'Arts and Science'), ('MANAGEMENT', 'Management'), ('LAW', 'Law'), ('ARCHITECTURE', 'Architecture')], db_index=True, max_length=50)),
                ('level', models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate')], db_index=True, max_length=2)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField()),
                ('image', models.URLField(blank=True, help_text='Image URL (external or asset path)', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'courses',
                'ordering': ['stream', 'name'],
                'indexes': [models.Index(fields=['stream', 'level'], name='courses_stream_97b2b4_idx')],
            },
        ),
    ]
