# Generated by Django 5.2.8 on 2025-12-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.URLField(blank=True, help_text='Image URL (external or asset path)', max_length=500, null=True),
        ),
    ]
